In [1]:
(1/6)*(4*27+54-42)

20.0

In [9]:
v = torch.tensor([1,2,3,4,5,6,7,8,9])
s=3
s0=1
L=2
v1 = torch.zeros((s0+1)*s**2)
countk = 0
for k in range(s):
    count = 0
    for i in range(s):
        for j in range(s0+1):
            v1[count+j*(s)+k*s*(s0+1)]= v[i+k*s]
            print(v1)
        count+=1
v1

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 0., 1., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 4., 0., 0., 4., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 4., 5., 0., 4., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 4., 5., 0., 4., 5., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 4., 5., 6., 4., 5., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 3., 4., 5., 6., 4., 5., 6., 0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 1., 2., 

tensor([1., 2., 3., 1., 2., 3., 4., 5., 6., 4., 5., 6., 7., 8., 9., 7., 8., 9.])

In [9]:
import torch
s = 3
s0 = 2
v = torch.arange(1,((s0+1)*s**2)+1)
v = v.view(s,(s0+1)*s)
for i in range(s):
    tmp = v[i,:].view(s0+1,s)

    if i==0:
        mat = tmp
    else:
        mat = torch.concat((mat,tmp),dim=1)



0
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
1
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])
2
tensor([[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])
tensor([[ 1,  2,  3, 10, 11, 12, 19, 20, 21],
        [ 4,  5,  6, 13, 14, 15, 22, 23, 24],
        [ 7,  8,  9, 16, 17, 18, 25, 26, 27]])
tensor([[ 1,  2,  3, 10, 11, 12, 19, 20, 21],
        [ 4,  5,  6, 13, 14, 15, 22, 23, 24],
        [ 7,  8,  9, 16, 17, 18, 25, 26, 27]])


In [10]:
import torch

s = 3
s0 = 2

# Create the initial tensor
v = torch.arange(1, (s0 + 1) * s ** 2 + 1)

# Directly reshape and transpose without explicit looping
v = v.view(s, s0 + 1, s).transpose(0, 1).reshape(s * (s0 + 1), s)

# Now v is equivalent to the mat in your original code
print(v)

tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21],
        [ 4,  5,  6],
        [13, 14, 15],
        [22, 23, 24],
        [ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27]])


In [12]:
import torch
s =3
s0 =1
L=2
v = torch.arange(1,19)
print(v)
v=v.view(-1,s)
# Reshape the tensor to (s, s0+1, s)
v = v.view(s, s0 + 1, s)
print(v)
# Sum over the second dimension
v = v.sum(dim=1)
print(v)
v.view(s**2)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
tensor([[ 5,  7,  9],
        [17, 19, 21],
        [29, 31, 33]])


tensor([ 5,  7,  9, 17, 19, 21, 29, 31, 33])

In [1]:
import torch
from lcn import LocallyHierarchicalNet
from lcn_shared import LocallyHierarchicalNetShared

net = LocallyHierarchicalNetShared(
    num_layers=2,
    input_channels=1,
    h=1,
    # filter_size=args.filter_size,
    out_dim=1,
    s =2,
    s0 = 1,
    sharing = 2, 
    bias=None,
)

1 1
1 1


In [3]:
s=2
s0=1
L=2
print(net.hier[0].weight.shape)
x = torch.zeros([1,1,(s*(s0+1))**L])
for j in range((s*(s0+1))**L):
    x[0,0,j] = j+1

print(x.shape)
print(net(x))


torch.Size([1, 1, 4])
torch.Size([1, 1, 16])
sharing self
2
before anything
tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16.]]])
torch.Size([1, 1, 2, 4])
torch.Size([1, 1, 4])
0
torch.Size([1, 1, 4, 1])
torch.Size([1, 1, 4])
one instance of s0
tensor([[[ 3.,  7., 19., 23.]]])
Parameter containing:
tensor([[[1.8860, 0.6315, 0.5515, 0.2825]]], requires_grad=True)
x:torch.Size([1, 1, 1, 4])
1
torch.Size([1, 1, 4, 1])
torch.Size([1, 1, 4])
one instance of s0
tensor([[[11., 15., 27., 31.]]])
Parameter containing:
tensor([[[1.8860, 0.6315, 0.5515, 0.2825]]], requires_grad=True)
x:torch.Size([1, 1, 1, 2, 4])
final
torch.Size([1, 1, 4])
sharing self
0
before anything
tensor([[[10.0787, 16.9763, 30.2189, 23.6483]]], grad_fn=<ReluBackward0>)
tensor([[21.6473]], grad_fn=<DivBackward0>)


In [1]:
import torch 
#NOT SHARED
bs = 2
cin = 4
cout = 10
d = 4 #s=2, s0=0, L=2
x = torch.zeros([bs,cin,d])
w = torch.zeros([cout,cin,d])
print(x.shape)
print(x[:,None].shape)
print(w.shape)
x = x[:,None]*w
print(x.shape)

x = x.view(bs, cout, cin, d // 2, 2) # [bs, cout, cin, space // 2, 2]
#*x.shape[:-1]

x = x.sum(dim=[-1, -3])
print(x.shape)

KeyboardInterrupt: 

In [13]:
import torch 
#SHARED
bs = 2
cin = 5
cout = 10
s= 2
s0 =1
L=1
d = (s*(s0+1))**L

x = torch.zeros([bs,cin,d])
w = torch.zeros([cout,cin,int(d/(s0+1))])
print(x.shape)
#print(w.shape)

x = x.reshape(*x.shape[:-1], int(x.shape[-1]/(s0+1)),s0+1)
x = x.sum(dim = [-1])
print(x.shape)
x = x[:,None]*w
print(x.shape)

x = x.view(bs, cout, cin, d // (s*(s0+1)), s) # [bs, cout, cin, space // 2, 2]
#*x.shape[:-1]

x = x.sum(dim=[-1, -3])
print(x.shape)


torch.Size([2, 5, 4])
torch.Size([2, 5, 2])
torch.Size([2, 10, 5, 2])
torch.Size([2, 10, 1])
